basePath: /
definitions:
  handler.InstanceActionRequest:
    properties:
      action:
        $ref: '#/definitions/workflow.TaskAction'
      actor_id:
        type: string
      comment:
        type: string
    type: object
  handler.RegisterFlowRequest:
    properties:
      code:
        type: string
      description:
        type: string
      name:
        type: string
      nodes:
        items:
          $ref: '#/definitions/workflow.FlowNode'
        type: array
    type: object
  handler.StartInstanceRequest:
    properties:
      business_id:
        type: string
      created_by:
        type: string
      space_id:
        type: string
    type: object
  handler.WFErrorResponse:
    properties:
      error:
        type: string
    type: object
  workflow.FlowDefinition:
    properties:
      code:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      nodes:
        items:
          $ref: '#/definitions/workflow.FlowNode'
        type: array
      updated_at:
        type: string
    type: object
  workflow.FlowInstance:
    properties:
      business_id:
        type: string
      completed_at:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      current_node_id:
        type: string
      definition_id:
        type: string
      history:
        items:
          $ref: '#/definitions/workflow.InstanceAction'
        type: array
      id:
        type: string
      space_id:
        type: string
      status:
        $ref: '#/definitions/workflow.InstanceStatus'
      updated_at:
        type: string
    type: object
  workflow.FlowNode:
    properties:
      approver_role:
        type: string
      id:
        type: string
      name:
        type: string
      next_node_id:
        type: string
      type:
        $ref: '#/definitions/workflow.FlowNodeType'
    type: object
  workflow.FlowNodeType:
    enum:
    - approval
    - auto
    type: string
    x-enum-varnames:
    - NodeTypeApproval
    - NodeTypeAuto
  workflow.InstanceAction:
    properties:
      action:
        $ref: '#/definitions/workflow.TaskAction'
      actor_id:
        type: string
      comment:
        type: string
      created_at:
        type: string
      id:
        type: string
      instance_id:
        type: string
      node_id:
        type: string
    type: object
  workflow.InstanceStatus:
    enum:
    - pending
    - approved
    - rejected
    type: string
    x-enum-varnames:
    - StatusPending
    - StatusApproved
    - StatusRejected
  workflow.TaskAction:
    enum:
    - approve
    - reject
    type: string
    x-enum-varnames:
    - ActionApprove
    - ActionReject
info:
  contact: {}
  description: Workflow orchestration endpoints for the knowledge base.
  title: Knowledge Base Workflow Service API
  version: 0.1.0
paths:
  /api/flows:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/workflow.FlowDefinition'
            type: array
      security:
      - BearerAuth: []
      summary: List workflow definitions
      tags:
      - Definitions
    post:
      consumes:
      - application/json
      parameters:
      - description: Definition payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterFlowRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/workflow.FlowDefinition'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.WFErrorResponse'
      security:
      - BearerAuth: []
      summary: Register workflow definition
      tags:
      - Definitions
  /api/flows/{code}/instances:
    post:
      consumes:
      - application/json
      parameters:
      - description: Definition code
        in: path
        name: code
        required: true
        type: string
      - description: Instance payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.StartInstanceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/workflow.FlowInstance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.WFErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.WFErrorResponse'
      security:
      - BearerAuth: []
      summary: Start workflow instance
      tags:
      - Instances
  /api/instances/{id}:
    get:
      parameters:
      - description: Instance ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/workflow.FlowInstance'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.WFErrorResponse'
      security:
      - BearerAuth: []
      summary: Get workflow instance
      tags:
      - Instances
  /api/instances/{id}/actions:
    post:
      consumes:
      - application/json
      parameters:
      - description: Instance ID
        in: path
        name: id
        required: true
        type: string
      - description: Action payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.InstanceActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/workflow.FlowInstance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.WFErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.WFErrorResponse'
      security:
      - BearerAuth: []
      summary: Submit action on workflow instance
      tags:
      - Instances
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
