server:
  host: localhost
  port: "8080"

database:
  host: localhost
  port: "5432"
  user: postgres
  password: password
  dbname: kb_platform
  sslmode: disable

jwt:
  secret: GdQZZu8HGP1BlENVCyPjqv2j7a0fAGUuE99k+Zde+hh4V1BBGGJVduGvAPeeZg55FzcFTr7xhDXNK5Gn66TmaQ==
  expire_time: 24

log:
  level: info
  db_log_level: warn
