// Package iam Code generated by swaggo/swag. DO NOT EDIT
package iam

import "github.com/swaggo/swag"

const docTemplateiam = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoiam holds exported Swagger Info so clients can modify it
var SwaggerInfoiam = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Knowledge Base IAM Service API",
	Description:      "Account and permission management endpoints for the knowledge base.",
	InfoInstanceName: "iam",
	SwaggerTemplate:  docTemplateiam,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoiam.InstanceName(), SwaggerInfoiam)
}
