basePath: /
info:
  contact: {}
  description: Account and permission management endpoints for the knowledge base.
  title: Knowledge Base IAM Service API
  version: 0.1.0
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
