spring:
  application:
    name: kb-platform
  
  # Jackson Configuration - 使用下划线命名与Go版本保持一致
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  # R2DBC Configuration (Reactive Database)
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kb_platform
    username: myuser
    password: mysecretpassword
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
  
  # Security Configuration
  security:
    jwt:
      secret: rn+kMwL25dI0vnzs+DdY16Eca6o6F7BHBNU13AJi/6SU4rTiJ/EyNzwR8bLVjwuxk3XbdYwMx7cv7CA8W4iXlw==
      expiration: 86400000 # 24 hours in milliseconds
      refresh-expiration: 604800000 # 7 days in milliseconds

# Application Configuration
app:
  # MinIO Configuration
  minio:
    endpoint: https://api.kunxiangtech.com:9000
    access-key: tIib6uMMDCUgujlicB3B
    secret-key: 38lmILFSwAZUR9Rl155VYVlCgKNbZe7jIfY9EmoF
    bucket-name: kb-platform
    secure: false
  
  # OpenAI Configuration
  openai:
    api-key: sk-eM1CKOeVcmjqjIA7jZiRyMDXq1PwQo5i9Vi08njyxEicKcPt
    base-url: https://api.chatanywhere.tech/v1
    model: gpt-4o-mini
    embedding-model: text-embedding-3-small
    timeout: 60s
  
  # Qdrant Configuration
  qdrant:
    host: localhost
    port: 6333
    api-key: ""
    collection-name: kb_documents
    vector-size: 1024
    use-https: false
  
  # PaddleOCR Configuration
  paddle-ocr:
    url: http://localhost:8500
    enabled: true
  
  # Workflow Configuration
  workflow:
    default-timeout-hours: 24
    max-retry-count: 3

# Server Configuration
server:
  port: 8080
  http2:
    enabled: true

# Logging Configuration
logging:
  level:
    root: WARN
    com.knowledgebase.platformspring: DEBUG
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.r2dbc: WARN
    org.springframework.data.r2dbc: WARN
    reactor.netty: WARN
    io.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    # 注意：Reactor Context 中的 requestId 需要在代码中手动添加到日志
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30

# Management Endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true
