apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: kb-platform
  labels:
    app: gateway
    version: v1.0.0
data:
  KBASE_ENV: "production"
  KBASE_SERVER_HOST: "0.0.0.0"  
  KBASE_SERVER_PORT: "8080"
  KBASE_IAM_URL: "http://iam-service:8081"
  KBASE_WORKFLOW_URL: "http://workflow-service:8082"
  KBASE_KB_URL: "http://kb-service:8083"
  KBASE_GIN_MODE: "release"
  KBASE_LOG_LEVEL: "warn"
  KBASE_LOG_DB_LOG_LEVEL: "silent"