apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-config
  namespace: kb-platform
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: "8080"
    
    database:
      host: "postgres-master-service"
      port: "5432"
      user: "postgres"
      password: "postgres123"
      dbname: "kb-platform"
      sslmode: "disable"
    
    jwt:
      secret: "your-secret-key-change-this-in-production"
      expire_time: 24
