apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-config
  namespace: kb-platform
  labels:
    app: iam
    version: v1.0.0
data:
  KBASE_ENV: localtest
  KBASE_SERVER_HOST: localhost
  KBASE_SERVER_PORT: 8081
  KBASE_DATABASE_HOST: postgres-master-service
  KBASE_DATABASE_PORT: 5432
  KBASE_DATABASE_USER: 
    valueFrom:
      secretKeyRef:
        name: iam-secret
        key: DATABASE_USER
  KBASE_DATABASE_PASSWORD: 
    valueFrom:
      secretKeyRef:
        name: iam-secret
        key: DATABASE_PASSWORD
  KBASE_DATABASE_DBNAME: kb_platform
  KBASE_DATABASE_SSLMODE: enable
  KBASE_JWT_SECRET: 
    valueFrom:
      secretKeyRef:
        name: iam-secret
        key: JWT_SECRET
  KBASE_JWT_ACCESS_TOKEN_EXPIRE_TIME: 1
  KBASE_JWT_REFRESH_TOKEN_EXPIRE_TIME: 24
  KBASE_LOG_LEVEL: warn
  KBASE_DB_LOG_LEVEL: error
  KBASE_GIN_MODE: release
  KBASE_LOG_DB_LOG_LEVEL: error