apiVersion: v1
kind: ConfigMap
metadata:
  name: kb-service-config
  namespace: kb-platform
  labels:
    app: kb-service
    version: v1.0.0
data:
  KBASE_ENV: "production"
  KBASE_SERVER_HOST: "0.0.0.0"
  KBASE_SERVER_PORT: "8083"
  KBASE_DATABASE_HOST: "postgres-master-service"
  KBASE_DATABASE_PORT: "5432"
  KBASE_DATABASE_DBNAME: "kb_platform"
  KBASE_DATABASE_SSLMODE: "disable"
  KBASE_LOG_LEVEL: "warn"
  KBASE_DB_LOG_LEVEL: "error"
  KBASE_GIN_MODE: "release"
  KBASE_LOG_DB_LOG_LEVEL: "error"
  KBASE_IAM_URL: "http://iam-service:8081"
  KBASE_WORKFLOW_URL: "http://workflow-service:8082"
