// Package workflow Code generated by swaggo/swag. DO NOT EDIT
package workflow

import "github.com/swaggo/swag"

const docTemplateworkflow = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoworkflow holds exported Swagger Info so clients can modify it
var SwaggerInfoworkflow = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Knowledge Base Workflow Service API",
	Description:      "Workflow orchestration endpoints for the knowledge base.",
	InfoInstanceName: "workflow",
	SwaggerTemplate:  docTemplateworkflow,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoworkflow.InstanceName(), SwaggerInfoworkflow)
}
