apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: kb-platform
  labels:
    app: iam
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
        version: v1.0.0
    spec:
      containers:
        - name: iam
          image: harbor.kunxiangtech.com:8443/kb-platform/iam:v1.0.1
          ports:
            - containerPort: 8081
              name: http
          envFrom:
            - configMapRef:
                name: iam-config
            - secretRef:
                name: iam-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: iam-service
  namespace: kb-platform
  labels:
    app: iam
    version: v1.0.0
spec:
  selector:
    app: iam
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
