apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-service
  namespace: kb-platform
  labels:
    app: kb-service
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kb-service
  template:
    metadata:
      labels:
        app: kb-service
        version: v1.0.0
    spec:
      containers:
        - name: kb-service
          image: harbor.kunxiangtech.com:8443/kb-platform/kb-service:v1.0.1
          ports:
            - containerPort: 8083
              name: http
          envFrom:
            - configMapRef:
                name: kb-service-config
            - secretRef:
                name: kb-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: kb-service
  namespace: kb-platform
  labels:
    app: kb-service
    version: v1.0.0
spec:
  selector:
    app: kb-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
