apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  namespace: kb-platform
  labels:
    app: workflow
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
        version: v1.0.0
    spec:
      containers:
        - name: workflow
          image: harbor.kunxiangtech.com:8443/kb-platform/workflow:v1.0.0
          ports:
            - containerPort: 8082
              name: http
          envFrom:
            - configMapRef:
                name: workflow-config
            - secretRef:
                name: workflow-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: kb-platform
  labels:
    app: workflow
    version: v1.0.0
spec:
  selector:
    app: workflow
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
