server:
  host: localhost
  port: "8083"

iam:
  url: http://localhost:8081

workflow:
  url: http://localhost:8082

gin:
  mode: debug

database:
  host: localhost
  port: "5432"
  user: postgres
  password: password
  dbname: kb_platform
  sslmode: disable

log:
  level: debug
  db_log_level: warn

minio:
  endpoint: api.kunxiangtech.com:9000
  access_key: tIib6uMMDCUgujlicB3B
  secret_key: 38lmILFSwAZUR9Rl155VYVlCgKNbZe7jIfY9EmoF
  bucket: kb-platform
  region: us-east-1

ocr:
  base_url: http://localhost:8500
  timeout_seconds: 600
  language: ch

vector:
  base_url: http://localhost:6333
  api_key: ""
  collection: kb_documents
  vector_size: 768  # Jina embeddings-v3 向量维度
  distance: Cosine
  timeout_seconds: 30

openai:
  # url: https://api.deepseek.com/v1  # 用于chat
  # api_key: sk-bd26f4335716448889f4be844fb8e4a3

  # embedding_url: https://api.jina.ai/v1
  # embedding_api_key: jina_852e03eb2f084084886ddbc2a447be751ABxRjI7yCutvf00nLsUw-_RQ-rg
  # embedding_model: jina-embeddings-v4
  url: http://182.140.132.5:11434/v1  # 用于chat
  api_key: "111"
  model: qwen2.5:0.5b

  embedding_url: http://182.140.132.5:11434/v1
  embedding_api_key: "111"
  embedding_model: nomic-embed-text:latest

