apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-spring
  namespace: kb-platform
  labels:
    app: platform-spring
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-spring
  template:
    metadata:
      labels:
        app: platform-spring
        version: v1.0.0
    spec:
      containers:
        - name: platform-spring
          image: harbor.kunxiangtech.com:8443/kb-platform/platform-spring:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            # 从 ConfigMap 批量导入环境变量
            - configMapRef:
                name: platform-spring-config
            # 从 Secret 批量导入敏感信息
            - secretRef:
                name: platform-spring-secret
          
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      
      volumes:
        - name: logs
          emptyDir: {}
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: platform-spring-service
  namespace: kb-platform
  labels:
    app: platform-spring
    version: v1.0.0
spec:
  selector:
    app: platform-spring
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  sessionAffinity: None

