apiVersion: v1
kind: Secret
metadata:
  name: platform-spring-secret
  namespace: kb-platform
  labels:
    app: platform-spring
    version: v1.0.0
type: Opaque
stringData:
  # Database Password
  SPRING_R2DBC_PASSWORD: "password"
  
  # JWT Secret (请替换为实际的密钥)
  JWT_SECRET: "SsvYrEOIzdgebLbd+Q8YnkdmOWKgTTzL8JNL69xx9fMhUnzZGCG08VplUbeNlWCbXvjYpHLJwMnASP/0YI8Uw=="
  
  # MinIO Credentials
  MINIO_ACCESS_KEY: "tIib6uMMDCUgujlicB3B"
  MINIO_SECRET_KEY: "38lmILFSwAZUR9Rl155VYVlCgKNbZe7jIfY9EmoF"

