apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-spring
  namespace: kb-platform
  labels:
    app: platform-spring
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-spring
  template:
    metadata:
      labels:
        app: platform-spring
        version: v1.0.0
    spec:
      containers:
        - name: platform-spring
          image: harbor.kunxiangtech.com:8443/kb-platform/platform-spring:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            # 从 ConfigMap 读取环境变量
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: SERVER_PORT
            - name: SPRING_R2DBC_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: SPRING_R2DBC_URL
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: SPRING_R2DBC_USERNAME
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: MINIO_ENDPOINT
            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: MINIO_BUCKET_NAME
            - name: OPENAI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: OPENAI_BASE_URL
            - name: OPENAI_MODEL
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: OPENAI_MODEL
            - name: QDRANT_HOST
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: QDRANT_HOST
            - name: QDRANT_PORT
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: QDRANT_PORT
            - name: PADDLE_OCR_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: PADDLE_OCR_URL
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: platform-spring-config
                  key: JAVA_OPTS
            
            # 从 Secret 读取敏感信息
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-spring-secret
                  key: SPRING_R2DBC_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-spring-secret
                  key: JWT_SECRET
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-spring-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-spring-secret
                  key: MINIO_SECRET_KEY
          
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      
      volumes:
        - name: logs
          emptyDir: {}
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: platform-spring-service
  namespace: kb-platform
  labels:
    app: platform-spring
    version: v1.0.0
spec:
  selector:
    app: platform-spring
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  sessionAffinity: None

