server:
  host: "0.0.0.0"
  port: "8082"

gin:
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "workflow"
  sslmode: "disable"

log:
  level: "info"
  db_log_level: "warn"