server:
  host: localhost
  port: "8082"

database:
  host: localhost
  port: "5432"
  user: postgres
  password: password
  dbname: workflow
  sslmode: disable

log:
  level: info
  db_log_level: warn

gin:
  mode: debug