version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: iam_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro

  iam:
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile.iam
    environment:
      IAM_SERVER_HOST: 0.0.0.0
      IAM_SERVER_PORT: 8080
      IAM_AUTH_JWT_SIGNING_KEY: dev-secret
      IAM_DATABASE_DSN: postgres://postgres:postgres123@postgres:5432/iam_platform?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  workflow:
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile.workflow
    environment:
      WORKFLOW_SERVER_HOST: 0.0.0.0
      WORKFLOW_SERVER_PORT: 8090
      WORKFLOW_AUTH_JWT_SIGNING_KEY: dev-secret
      WORKFLOW_DATABASE_DSN: postgres://postgres:postgres123@postgres:5432/iam_platform?sslmode=disable
    ports:
      - "8090:8090"
    depends_on:
      - postgres

volumes:
  pgdata:
