definitions:
  model.Permission:
    properties:
      action:
        type: string
      created_at:
        type: string
      description:
        type: string
      display_name:
        type: string
      id:
        type: integer
      name:
        type: string
      resource:
        type: string
      roles:
        description: 关联关系
        items:
          $ref: '#/definitions/model.Role'
        type: array
      updated_at:
        type: string
    type: object
  model.Role:
    properties:
      created_at:
        type: string
      description:
        type: string
      display_name:
        type: string
      id:
        type: integer
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/model.Permission'
        type: array
      status:
        type: integer
      updated_at:
        type: string
      users:
        description: 关联关系
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.User:
    properties:
      avatar:
        type: string
      company:
        type: string
      created_at:
        type: string
      department:
        type: string
      email:
        type: string
      id:
        type: integer
      last_login:
        type: string
      nickname:
        type: string
      phone:
        type: string
      roles:
        description: 关联关系
        items:
          $ref: '#/definitions/model.Role'
        type: array
      status:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  service.ChangePasswordRequest:
    properties:
      new_password:
        minLength: 6
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  service.LoginRequest:
    properties:
      login:
        description: 支持用户名、手机号、邮箱登录
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  service.LoginResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/model.User'
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/change-password:
    patch:
      consumes:
      - application/json
      description: 修改密码
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 修改密码请求
        in: body
        name: change_password_request
        required: true
        schema:
          $ref: '#/definitions/service.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: 修改密码
      tags:
      - Auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 登录请求
        in: body
        name: login_request
        required: true
        schema:
          $ref: '#/definitions/service.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 登录
      tags:
      - Auth
swagger: "2.0"
